### ISSUE TITLE
get() and formatMessage() returns empty string instead of key

### ISSUE THREAD

**Issue by zcoffin86** [alibaba/react-intl-universal#141]
In issue #2 there is the thought that this project should mirror the react-intl API. I've been migrating a project to use this library and I just ran into a case where it doesn't.

When using `get()` with a key that is not present in the locale files (or `formatMessage()`), `react-intl` displays a console warning and returns the key, whereas currently `react-intl-universal` displays a console warning and returns an empty string. This was caught in testing of our application and gives me slight pause, since I'm not 100% confident that there aren't any other areas of our application that are currently relying on this fallback behavior.

Put another way:
When using `react-intl` and `formatMessage()` or `<FormattedMessage />` it will fallback to presenting the key you requested in the event that the key is not found in the `locale.json` translation file. However, in `react-intl-universal` when using `intl.get()` the fallback is to an empty string. In either case, you will get a console warning, and ideally developers are testing their code and resolving any console warnings before committing, but cases that rely on this fallback behavior may exist in any given application.

**Comment by cwtuan** [comment]
Hi, @zcoffin86
Thanks for the contribution.
However, this PR may not be accepted since this change the behavior in current API.
We recommend use defaultMessage for every message in case that the key is not found.
For example, intl.get('HELLO', { name }).d(`Hello, ${name}`)
You could also add warningHandler in init function to accumulate missing messages using third party services.
